name: Deploy MultiDocker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Run client tests
        working-directory: ./complex
        run: |
          docker build -t joelpriddy/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true joelpriddy/react-test npm test
      - name: Build images
        working-directory: ./complex
        run: |
          docker build -t joelpriddy/multi-client ./client
          docker build -t joelpriddy/multi-nginx ./nginx
          docker build -t joelpriddy/multi-server ./server
          docker build -t joelpriddy/multi-worker ./worker
      - name: Push images to DockerHub
        working-directory: ./complex
        run: |
          docker push joelpriddy/multi-client
          docker push joelpriddy/multi-nginx
          docker push joelpriddy/multi-server
          docker push joelpriddy/multi-worker
